jusylopes/koru-mobile-projeto-3

classes/pessoa.dart
- Adição de método calcular idade;
=> feat: criar metodo calcular idade

classes/produto.dart
=> feat: criar class produto

classes/pessoa.dart
-Adição de classe Pessoa e seus atributos;
=> feat: criar classe Pessoa

classes/produto.dart
- Adição de método ver receita gerada.
=> feat: criar metodo receita gerada

classes/produto.dart
##📝 Changelog
- Adição de método realizar venda;
=> feat: criar metodo realizarVenda

classes/pessoa.dart
- Adição de método maior idade;
=> feat: criar metodo maior idade

main.dart
- Adição de teste de saída da classe pessoa;
=> feat: teste de saida da classe pessoa

classes/pessoa.dart
- Refatoração no método calcular idade;
=> refactor: metodo calcular idade

main.dart
##📝 Changelog
Adição dos testes de saída da classe Produto;
=> feat: teste de saida da classe produto

classes/revendedor.dart
- Adição de classe revendedor atributos;
‌
=> feat: criar classe revendedor

classes/cliente.dart
=> feat: criar classe cliente

classes/cliente.dart
- Sobrescrita de método falar;
=> feat: override de metodo falar

classes/enums.dart
- Criação de enum chamado Genero, contendo os gêneros: Feminino, Masculino, Outro
=> feat: criar enum genero

classes/cliente.dart
- criar método adicionar dinheiro;
=> feat: criar método adicionar dinheiro

classes/revendedor.dart
- Adição de método realizar venda;
‌
=>  feat: criar metodo realizarVenda

classes/cliente.dart, classes/pessoa.dart, classes/revendedor.dart, main.dart
- Adição do parametro genero na classe pessoa.
=> feat: criar parametro genero

classes/cliente.dart
- Adição de método comprar produto;
=> feat: criar metodo comprar produto

main.dart
- Adição de teste de saída classe cliente.
=> feat: criar teste de saida da classe cliente

classes/cliente.dart, classes/produto.dart, classes/revendedor.dart, main.dart, utils.dart
- Bugfix de método comprar produto;
- Correção de nome da variável porcentagemLucro;
- Ajuste na porcentagem de lucro;
- Refatoração de métodos venderProduto e realizarVenda para boolean;
=> fix: retorno metodo comprar produto

classes/cliente.dart, main.dart
- Adição de método ver saldo;
‌
=> feat: criar metodo ver saldo atual

main.dart, utils.dart
- Adição de impressão de receita gerada do produto.
‌
=> feat: criar metodo imprimir receita gerada

README.md, classes/cliente.dart, classes/enums.dart, classes/pessoa.dart, classes/produto.dart, classes/revendedor.dart, main.dart, utils.dart
=> chore: release version 2.0.0

classes/cliente.dart, classes/pessoa.dart, main.dart, utils.dart
- Adição de método ordenar produtos comprados na classe cliente;
=> feat: criar metodo ordenar produtos comprados 

classes/cliente.dart, classes/produto.dart, classes/revendedor.dart
- Refatoração de método realizar venda;
=> feat: refatorar metodo realizarVenda

classes/cliente.dart
- Adição de método criar método calcular total de gasto ;
=> feat: criar metodo calcular total de gasto

classes/revendedor.dart
- Correção do método para calcular média dos produtos vendidos;
‌
=> Fix: criar metodo calcular media produtos vendidos

classes/cliente.dart
- Refatoração de método comprar produto;
=> feat: refatoracao metodo comprar produto

main.dart, utils.dart
- Adição de  ASCII art nas saídas do console
=> style: inserir ASCII art nas saídas do console

classes/cliente.dart
- Adição de método verResultado
=> feat: criar metodo verResultado

classes/cliente.dart, main.dart
- Adição de método ver produtos comprados;
=> feat: criar metodo ver produtos comprados

classes/revendedor.dart
- Adição de método Calcular Total Vendido;
=> feat: Criar metodo calcular total vendido

classes/revendedor.dart
- Adição de método calcular lucro;
=> feat: criar metodo calcular lucro

PULL_REQUEST_TEMPLATE.md, classes/brinde.dart, classes/pessoa.dart, classes/revendedor.dart
- Adição de método realizar troca;
- Classe Brinde - Alteração na variável qtdEmEstoque para privada;
- Classe Revendedor - Alteração na variável porcentagemLucro para privada.
-  Add mensagem padrão de PR
=> feat: criar metodo realizar troca

classes/revendedor.dart
- Chamar metodo calcularTotalVendido para cálculo de produtos da média;
=> refactor: chamar metodo calcularTotalVendido para media

utils/enums.dart
- Adição de método pessoa Enum-Humor
=> feat: criar metodo enumHumor

classes/cliente.dart
- Refatorização do atributo brindes;
=> feat: refatorar atributo brindes

classes/cliente.dart, utils/mock_revendedor.dart
=> feat: add dados mock revendedor

classes/cliente.dart
- Adição de método ver brindes;
=> feat: criar metodo ver brindes

utils/mock_brinde.dart
- Adição de dados mock brinde;
=> feat: add dados mock brinde

classes/cliente.dart
- Adição de método consultar pontos.
=> feat: metodo consultar pontos

classes/pessoa.dart
- Adição de método termômetro do humor;
=> feat: criar metodo termometro do humor

classes/cliente.dart, classes/produto.dart, classes/revendedor.dart
- Bugfix chamada de metodo falar;
- Ajustes na saida de verResumo.
=> fix: revendedor metodo falar

classes/revendedor.dart, menu_interativo/menu_cliente.dart, menu_interativo/menu_clube_de_fidelidade.dart, menu_interativo/menu_revendedor.dart, menu_interativo/utils_menu.dart
- Adição de menu termômetro do humor;
- Refatoração menu revendedor, cliente, clube de fidelidade;
- Fix  termômetro do humor.
=> feat:  criar menu termometro do humor
